variables:
  SSH_PATH: 'C:\Windows\System32\OpenSSH\ssh.exe'
  SCP_PATH: 'C:\Windows\System32\OpenSSH\scp.exe'
stages:
  - build_deploy
  - deploy

build:
  stage: build_deploy

  script:
    - '.\ssh.exe -i "C:/Users/user/Desktop/PJH/marketing blog/keys/ssh_key_openssh" biyajunior@34.64.238.235 "sudo service marketing-blog stop"'
    - 'mvn package -Dmaven.test.skip=true'
    - '.\scp.exe -i "C:/Users/user/Desktop/PJH/marketing blog/keys/ssh_key_openssh" marketing-blog.jar biyajunior@34.64.238.235:/home/biyajunior/marketing-blog/app/marketing-blog.jar'
    - '.\ssh.exe -i "C:/Users/user/Desktop/PJH/marketing blog/keys/ssh_key_openssh" biyajunior@34.64.238.235 "sudo service marketing-blog start"'
  only:
    - master
  tags:
    - JHPARK
    - WINDOWS

deploy:
  stage: deploy
  script:
    # - if [ ! -f ci_settings.xml ];
    #     then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
    #   fi
    # - 'mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml'
    - 'ls -al'
    - 'cd target'
    - 'ls -al'
    
  when: manual
  only:
    - master

  
