logging:
  file:
    path: /home/ec2-user/blog/log/
  pattern:
    file: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'


spring:
  profiles:
    include: file-logging
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://blog.yonilum.com/login/oauth2/code/kakao

app-security:
  oauth2:
    authorizedRedirectUris:
      - http://blog.yonilum.com/oauth2/redirect