server:
  error:
    include-exception: true
    include-stacktrace: always
    path: /error
    whitelabel:
      enabled: true
  port: 8080


spring:
  freemarker:
    cache: false
    check-template-location: true
    prefix: /
    settings:
      auto_import: /spring.ftl as spring
      number_format: computer
    suffix: .ftl
    template-loader-path: classpath:/templates
    resources:
      static-locations: classpath:/static

  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Qlalflek12{*
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        use-sql-comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  security:
    oauth2:
      client:
        # 나만의 Setting
        registration:
          kakao:
            client-id: d34e659e3758a5d45c8a27764f537839
            client-secret: uP7rtfeWdwksjwgJ0bHgMFSUie0OyA6C
#            redirect-uri: {baseUrl}/{action}/oauth2/code/{registrationId}
            redirect-uri: http://blog.yonilum.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
#            naver:
#              client-id: <your id>
#              client-secret: <your secret>
#              redirect-uri:  <your url>/login/oauth2/code/naver
#              authorization-grant-type: authorization_code
#              scope:
#                - name
#                - email
#            google:
#              client-id: <your id>
#              client-secret: your secret>
#              scope:
#                - profile
#                - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#              naver:
#                authorization-uri: https://nid.naver.com/oauth2.0/authorize
#                token-uri: https://nid.naver.com/oauth2.0/token
#                user-info-uri: https://openapi.naver.com/v1/nid/me
#                user-name-attribute: response


# JWT 관련
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC #JWT Token 을 Hash 할 때 사용하는 Secret Key
    tokenExpirationMsec: 864000000 # JWT Token의 유효기간
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.

    # 생성된 JWT Token을 response 할 uri
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect
#      - myandroidapp://oauth2/redirect
#      - myiosapp://oauth2/redirect



yonilum.access.token.key: YONITOKEN